/*
 *  Copyright 2013 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) google.targets; 1, 0, 0,88; 3-12-2013 15:04:47; /db/ztree/library/trees/xdctargets/xdctargets-g22x/src/ xlibrary

 */

