/*
 *  Copyright 2013 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,579; 3-12-2013 15:04:42; /db/ztree/library/trees/xdctargets/xdctargets-g22x/src/ xlibrary

 */

